version: '3.8'

services:
  jar:
    image: anapsix/alpine-java:latest
    container_name: prod_line
    restart: unless-stopped
    volumes:
      - ./java_export:/java_export
    command: ["java", "-jar", "/java_export/sort.jar"]
    depends_on:
      - mysql
      - redis
    network_mode: host
    # ports:
    #   - "8080:8080/tcp"
    # networks:
    #   prod_line:
    #     ipv4_address: 10.8.105.2
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/sort/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  mysql:
    image: mysql:8.0
    container_name: mysql_jinli
    restart: unless-stopped
    environment:
      # MYSQL_DATABASE: zsh_sort
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Hong_Kong
    volumes:
      - ./.data:/var/lib/mysql
      # - ./zsh_sort.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      --max_connections=1000
    network_mode: host
    privileged: true
    # ports:
    #   - "3306:3306/tcp"
    # networks:
    #   prod_line:
    #     ipv4_address: 10.8.105.3
    healthcheck:
      test: ["CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
  redis:
    image: redis/redis-stack:latest
    container_name: redis_jinli
    network_mode: host
    restart: unless-stopped
    # ports:
    #   - "6379:6379"
    # networks:
    #   prod_line:
    #     ipv4_address: 10.8.105.4

# networks:
#   prod_line:
#     ipam:
#       driver: default
#       config:
#         - subnet: 10.8.105.0/24
