version: '3.8'

services:
  core:
    image: anapsix/alpine-java:latest
    container_name: prod_line
    restart: always
    volumes:
      - ./java_export:/home/java_export
    command: java -jar /home/java_export/sort.jar
    ports:
      - "8080:8080/tcp"
    depends_on:
      - mysql
      - redis
    networks:
      prod_line:
        ipv4_address: 10.8.105.2
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8080/sort/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Hong_Kong
    volumes:
      - ./data:/var/lib/mysql
    command:
      --max_connections=1000
    ports:
      - "3306:3306/tcp"
    networks:
      prod_line:
        ipv4_address: 10.8.105.3
    healthcheck:
      test: ["CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      prod_line:
        ipv4_address: 10.8.105.4

networks:
  prod_line:
    driver: bridge
    config:
        - subnet: 10.8.105.0/24
